# Stage 1: Build the Java project with Maven
FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /RNM
COPY . .
RUN mvn clean package

# Stage 2: Create a minimal runtime image
FROM eclipse-temurin:21-jre-jammy
WORKDIR /usr/app

# Copy the built JAR from the builder stage
COPY --from=builder /RNM/target/ReliableNodeManagerOPE-0.1.0-jar-with-dependencies.jar .

# Expose ports for communication
EXPOSE 2050 2051 2052

# Start the ReliableNodeManager service
CMD ["java", "-jar", "ReliableNodeManagerOPE-0.1.0-jar-with-dependencies.jar", "0.0.0.0", "2050", "2051", "2052"]
