
package pt.isel.meic.iesd.rnm;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://pt.isel.meic.iesd.rnmtplm")
public class Exception_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private pt.isel.meic.iesd.rnm.Exception faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Exception_Exception(String message, pt.isel.meic.iesd.rnm.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public Exception_Exception(String message, pt.isel.meic.iesd.rnm.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: pt.isel.meic.iesd.rnm.Exception
     */
    public pt.isel.meic.iesd.rnm.Exception getFaultInfo() {
        return faultInfo;
    }

}
