# Stage 1: Build the Java project with Maven
FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /TM
COPY . .
RUN mvn clean package

# Stage 2: Create a minimal runtime image
FROM eclipse-temurin:21-jre-jammy
WORKDIR /usr/app

# Place java executable at /usr/app
COPY --from=builder /TM/target/TransactionManagerOPE-0.1.0-jar-with-dependencies.jar .

# The listening port
EXPOSE 2059

# Starts the TransactionManager service
CMD ["java","-jar","/usr/app/TransactionManagerOPE-0.1.0-jar-with-dependencies.jar"]
