
package pt.isel.meic.iesd.tm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "AxManagerService", targetNamespace = "http://tm.iesd.meic.isel.pt/", wsdlLocation = "http://localhost:2059/AX?wsdl")
public class AxManagerService
    extends Service
{

    private static final URL AXMANAGERSERVICE_WSDL_LOCATION;
    private static final WebServiceException AXMANAGERSERVICE_EXCEPTION;
    private static final QName AXMANAGERSERVICE_QNAME = new QName("http://tm.iesd.meic.isel.pt/", "AxManagerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:2059/AX?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AXMANAGERSERVICE_WSDL_LOCATION = url;
        AXMANAGERSERVICE_EXCEPTION = e;
    }

    public AxManagerService() {
        super(__getWsdlLocation(), AXMANAGERSERVICE_QNAME);
    }

    public AxManagerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AXMANAGERSERVICE_QNAME, features);
    }

    public AxManagerService(URL wsdlLocation) {
        super(wsdlLocation, AXMANAGERSERVICE_QNAME);
    }

    public AxManagerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AXMANAGERSERVICE_QNAME, features);
    }

    public AxManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AxManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IAX
     */
    @WebEndpoint(name = "AxManagerPort")
    public IAX getAxManagerPort() {
        return super.getPort(new QName("http://tm.iesd.meic.isel.pt/", "AxManagerPort"), IAX.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAX
     */
    @WebEndpoint(name = "AxManagerPort")
    public IAX getAxManagerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tm.iesd.meic.isel.pt/", "AxManagerPort"), IAX.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AXMANAGERSERVICE_EXCEPTION!= null) {
            throw AXMANAGERSERVICE_EXCEPTION;
        }
        return AXMANAGERSERVICE_WSDL_LOCATION;
    }

}
