
package pt.isel.meic.iesd.tm;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IAX", targetNamespace = "http://pt.isel.meic.iesd.tm.ax")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IAX {


    /**
     * 
     * @param resource
     * @param transactionID
     */
    @WebMethod
    @RequestWrapper(localName = "register", targetNamespace = "http://pt.isel.meic.iesd.tm.ax", className = "pt.isel.meic.iesd.tm.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://pt.isel.meic.iesd.tm.ax", className = "pt.isel.meic.iesd.tm.RegisterResponse")
    @Action(input = "http://pt.isel.meic.iesd.tm.ax/IAX/registerRequest", output = "http://pt.isel.meic.iesd.tm.ax/IAX/registerResponse")
    public void register(
        @WebParam(name = "transactionID", targetNamespace = "")
        int transactionID,
        @WebParam(name = "resource", targetNamespace = "")
        Resource resource);

    /**
     * 
     * @param resource
     * @param transactionID
     */
    @WebMethod
    @RequestWrapper(localName = "unregister", targetNamespace = "http://pt.isel.meic.iesd.tm.ax", className = "pt.isel.meic.iesd.tm.Unregister")
    @ResponseWrapper(localName = "unregisterResponse", targetNamespace = "http://pt.isel.meic.iesd.tm.ax", className = "pt.isel.meic.iesd.tm.UnregisterResponse")
    @Action(input = "http://pt.isel.meic.iesd.tm.ax/IAX/unregisterRequest", output = "http://pt.isel.meic.iesd.tm.ax/IAX/unregisterResponse")
    public void unregister(
        @WebParam(name = "transactionID", targetNamespace = "")
        int transactionID,
        @WebParam(name = "resource", targetNamespace = "")
        Resource resource);

}
