# Stage 1: Build the Java project with Maven
FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /TPLM
COPY . .
RUN mvn clean package

# Stage 2: Create a minimal runtime image
FROM eclipse-temurin:21-jre-jammy
WORKDIR /usr/app

# Place java executable at /usr/app
COPY --from=builder ./TPLM/target/TwoPhaseLockManagerOPE-1.0-SNAPSHOT-jar-with-dependencies.jar .

# The listening port
EXPOSE 3000

# Starts the TwoPhaseLockManager service
CMD ["java","-jar","/usr/app/TwoPhaseLockManagerOPE-1.0-SNAPSHOT-jar-with-dependencies.jar", "rabbitmq", "5672"]
